# Generated by Django 6.0.3 on 2026-03-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snippet', models.TextField()),
                ('language', models.CharField(default='python', max_length=50)),
                ('metrics', models.JSONField(default=dict)),
                ('ai_suggestion', models.TextField(blank=True, default='')),
                ('score', models.CharField(default='Low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
